config/routes.rb
Rails.application.routes.draw do

  scope module: 'edu' do
    resources :courses
  end

  scope :admin, module: 'edu/admin', as: 'admin' do
    
    resources :course_papers do
      get :add, on: :member
      resources :exams do
        put :refer, on: :member
        patch :score, on: :member
      end
    end
    resources :teachers do
      get :search, on: :collection
    end
    resources :exams, only: [] do
      get :todo, on: :collection
      get :cert, on: :collection
    end
  end

  scope :my, module: 'edu/my', as: 'my' do
    resources :exams, only: [] do
      post :add, on: :collection
      get :certification, on: :collection
    end
    resources :courses, only: [:index, :show] do
      collection do
        get :plan
      end
      resources :exams, shallow: true do
        match :finish, on: :member, via: [:get, :put]
      end
    end
    resources :course_students do
      get 'quit' => :edit_quit, on: :member
      patch 'quit' => :update_quit, on: :member
    end
    resource :teacher
  end

end

app/controllers/edu/my/base_controller.rb
class Edu::My::BaseController < RailsEdu.config.my_controller.constantize


end

app/controllers/edu/my/courses_controller.rb
class Edu::My::CoursesController < Edu::My::BaseController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    q_params = default_params
    @courses = Course.default_where(q_params).page(params[:page])
  end

  def plan
    @rooms = current

    q_params = {}.with_indifferent_access
    q_params.merge! params.permit(:room_id)
    @time_plans = TimePlan.default_where(q_params)
    @events = @time_plans.map do |time_plan|
      time_plan.next_events
    end.flatten

    respond_to do |format|
      format.html
      format.js
      format.json { render json: { events: @events } }
    end
  end


  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html.phone
        format.html { redirect_to edu_courses_url }
        format.js { redirect_back fallback_location: edu_courses_url }
        format.json { render :show }
      else
        format.html.phone { render :new }
        format.html { render :new }
        format.js { redirect_back fallback_location: edu_courses_url }
        format.json { render :show }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    @course.assign_attributes(course_params)

    respond_to do |format|
      if @course.save
        format.html.phone
        format.html { redirect_to edu_courses_url }
        format.js { redirect_back fallback_location: edu_courses_url }
        format.json { render :show }
      else
        format.html.phone { render :edit }
        format.html { render :edit }
        format.js { redirect_back fallback_location: edu_courses_url }
        format.json { render :show }
      end
    end
  end

  def destroy
    @course.destroy
    redirect_to edu_courses_url
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.fetch(:course, {}).permit(
    )
  end

end

app/controllers/edu/my/exams_controller.rb
class Edu::My::ExamsController < Edu::My::BaseController
  before_action :set_course, only: [:index, :new, :create]
  before_action :set_exam, only: [:show, :edit, :update, :finish, :destroy]

  def index
    @exams = @course.exams.where(member_id: current_member.id).page(params[:page])
    @course_papers = @course.course_papers.where.not(id: @exams.processing.pluck(:course_paper_id))
  end

  def certification
    q_params = {
      member_id: current_member.id,
      'course_paper.type': 'CertifiablePaper'
    }.with_indifferent_access
    @exams = Exam.default_where(q_params).page(params[:page])
    @course_papers = CertifiablePaper.where.not(id: @exams.pluck(:course_paper_id).uniq).page(params[:page])
  end

  def new
    @exam = Exam.new
  end

  def add
    @exam = current_member.exams.create(course_paper_id: params[:course_paper_id])
    @exam.reload
    @exam.custom_link
    #ExamGenerateJob.perform_later(@exam.id)

    if @exam.course_id
      redirect_to my_course_exams_url(@exam.course_id, course_paper_id: params[:course_paper_id])
    else
      redirect_to certification_my_exams_url
    end
  end

  def create
    @exam = Exam.new(exam_params)

    if @exam.save
      redirect_to my_course_exams_url(@course)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @exam.update(exam_params)
      redirect_to my_course_exams_url(@exam.course_id)
    else
      render :edit
    end
  end

  def finish
    @exam.set_finish
    if @exam.course_id
      redirect_to my_course_exams_url(@exam.course_id)
    else
      redirect_to cert_admin_exams_url
    end
  end

  def destroy
    @exam.destroy

    flash[:notice] = 'Exam was successfully destroyed.'
    if @exam.course_id
      redirect_to my_course_exams_url(@exam.course_id, course_paper_id: params[:course_paper_id])
    else
      redirect_to certification_my_exams_url
    end
  end

  private
  def set_course
    @course = Course.find params[:course_id]
  end

  def set_exam
    @exam = Exam.find(params[:id])
  end

  def exam_params
    params.fetch(:exam, {}).permit(
      :course_paper_id
    )
  end

end

app/controllers/edu/my/lesson_students_controller.rb
class Edu::My::LessonStudentsController < Edu::My::BaseController
  before_action :set_lesson_student, only: [:show, :edit, :update, :edit_quit, :update_quit, :destroy]

  def index
    q_params = {}.with_indifferent_access
    q_params.merge! params.fetch(:q, {}).permit!
    q_params.merge! params.permit('course.course_taxon_id', 'course.type', 'course.title-asc', :state)
    @lesson_students = current_member.lesson_students.includes(:course).default_where(q_params).page(params[:page])
  end

  def new
    @lesson_student = current_member.lesson_students.build
  end

  def create
    if params[:course_id]
      @lesson_student = current_member.lesson_students.build(course_id: params[:course_id])
    else
      @lesson_student = current_member.lesson_students.build(lesson_student_params)
    end

    if @lesson_student.save_with_remind
      redirect_to my_lesson_students_url
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @lesson_student.update(lesson_student_params)
      redirect_to my_lesson_students_url
    else
      render :edit
    end
  end

  def edit_quit
  end

  def update_quit
    @lesson_student.quit_note = lesson_student_params[:quit_note]
    @lesson_student.trigger_to! state: 'request_quit'
  end

  def destroy
    @lesson_student.destroy
    redirect_to my_lesson_students_url
  end

  private
  def set_lesson_student
    @lesson_student = LessonStudent.find(params[:id])
  end

  def lesson_student_params
    params.fetch(:lesson_student, {}).permit(
      :course_id,
      :quit_note
    )
  end

end

app/controllers/edu/my/lessons_controller.rb
class Edu::My::LessonsController < Edu::My::BaseController
  before_action :set_course, only: [:show, :edit]

  def index
    l_params = {
      'course.type': params[:type],
      'course.course_taxon_id': params[:course_taxon_id],
      'course.title-asc': params['title-asc']
    }
    @course_students = current_member.course_students.includes(:course).default_where(l_params)

    q_params = params.fetch(:q, {}).permit!
    q_params.merge! params.permit(:type, 'title-asc', :course_taxon_id)
    q_params.merge! 'id-not': @course_students.pluck(:course_id)
    # if current_member.department
    #   @courses = current_member.department.courses.default_where(q_params).page(params[:page])
    # else
      @courses = Course.outward.default_where(q_params).page(params[:page])
    #end

    respond_to do |format|
      format.html
      format.html.phone { render 'index', layout: 'my_phone' }
    end
  end

  def show

    respond_to do |format|
      format.html
      format.html.phone { render 'show', layout: 'my_phone' }
    end
  end

  private
  def set_course
    @course = Course.find(params[:id])
  end

end

app/controllers/edu/my/teachers_controller.rb
class Edu::My::TeachersController < Edu::My::BaseController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to my_teacher_url
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to my_teacher_url
    else
      render :edit
    end
  end

  def destroy
    @teacher.destroy
    redirect_to my_teacher_url
  end

  private
  def set_teacher
    @teacher = current_member&.teacher
  end

  def teacher_params
    params.fetch(:teacher, {}).permit(
      :description
    )
  end

end

app/controllers/train/admin/lessons_controller.rb
class TrainAdmin::LessonsController < TrainAdmin::BaseController
  before_action :set_lesson, only: [:show, :edit, :meet, :repeat_form, :update, :destroy]
  skip_before_action :verify_authenticity_token, only: [:repeat_form]

  def index
    q_params = params.fetch(:q, {}).permit!
    q_params.merge! params.permit(:type, :lesson_taxon_id, 'id-desc', 'id-asc', 'title-asc')
    if current_teacher
      @lessons = Lesson.default_where(q_params).permit_with(current_teacher).page(params[:page])
    else
      @lessons = Lesson.none.page
    end
  end

  def all
    q_params = params.fetch(:q, {}).permit!
    q_params.merge! params.permit(:type, :lesson_taxon_id, 'id-desc', 'id-asc', 'title-asc')
    @lessons = Lesson.default_where(q_params).page(params[:page])

    render 'index'
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)

    if @lesson.save
      redirect_to train_lessons_url, notice: 'Lesson was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to train_lesson_url(@lesson), notice: 'Lesson was successfully updated.' }
        format.js { head :no_content }
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  def meet

  end

  def destroy
    @lesson.destroy
    redirect_to train_lessons_url, notice: 'Lesson was successfully destroyed.'
  end

  private
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.fetch(:lesson, {}).permit(
      :lesson_taxon_id,
      :title,
      :description,
      :type,
      :position,
      :limit_people,
      :author_id,
      :lecturer_id,
      :meeting_room,
      :repeat_type,
      :start_at,
      :finish_at,
      :compulsory,
      video: [],
      en_video: [],
      document: [],
      repeat_days: [],
      department_ids: []
    )
  end

end

app/controllers/train/my/exams_controller.rb
class TrainMy::ExamsController < TrainMy::BaseController
  before_action :set_lesson, only: [:index, :new, :create]
  before_action :set_exam, only: [:show, :edit, :update, :finish, :destroy]

  def index
    @exams = @lesson.exams.where(member_id: current_member.id).page(params[:page])
    @lesson_papers = @lesson.lesson_papers.where.not(id: @exams.processing.pluck(:lesson_paper_id))
  end

  def certification
    q_params = {
      member_id: current_member.id,
      'lesson_paper.type': 'CertifiablePaper'
    }.with_indifferent_access
    @exams = Exam.default_where(q_params).page(params[:page])
    @lesson_papers = CertifiablePaper.where.not(id: @exams.pluck(:lesson_paper_id).uniq).page(params[:page])
  end

  def new
    @exam = Exam.new
  end

  def add
    @exam = current_member.exams.create(lesson_paper_id: params[:lesson_paper_id])
    @exam.reload
    @exam.custom_link
    #ExamGenerateJob.perform_later(@exam.id)

    if @exam.lesson_id
      redirect_to my_lesson_exams_url(@exam.lesson_id, lesson_paper_id: params[:lesson_paper_id])
    else
      redirect_to certification_my_exams_url
    end
  end

  def create
    @exam = Exam.new(exam_params)

    if @exam.save
      redirect_to my_lesson_exams_url(@lesson), notice: 'Exam was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @exam.update(exam_params)
      redirect_to my_lesson_exams_url(@exam.lesson_id), notice: 'Exam was successfully updated.'
    else
      render :edit
    end
  end

  def finish
    @exam.set_finish
    if @exam.lesson_id
      redirect_to my_lesson_exams_url(@exam.lesson_id)
    else
      redirect_to cert_train_exams_url
    end
  end

  def destroy
    @exam.destroy

    flash[:notice] = 'Exam was successfully destroyed.'
    if @exam.lesson_id
      redirect_to my_lesson_exams_url(@exam.lesson_id, lesson_paper_id: params[:lesson_paper_id])
    else
      redirect_to certification_my_exams_url
    end
  end

  private
  def set_lesson
    @lesson = Lesson.find params[:lesson_id]
  end

  def set_exam
    @exam = Exam.find(params[:id])
  end

  def exam_params
    params.fetch(:exam, {}).permit(
      :lesson_paper_id
    )
  end

end

app/controllers/train/my/lesson_members_controller.rb
class TrainMy::LessonMembersController < TrainMy::BaseController
  before_action :set_lesson_member, only: [:show, :edit, :update, :edit_quit, :update_quit, :destroy]

  def index
    q_params = {}.with_indifferent_access
    q_params.merge! params.fetch(:q, {}).permit!
    q_params.merge! params.permit('lesson.lesson_taxon_id', 'lesson.type', 'lesson.title-asc', :state)
    @lesson_members = current_member.lesson_members.includes(:lesson).default_where(q_params).page(params[:page])
  end

  def new
    @lesson_member = current_member.lesson_members.build
  end

  def create
    if params[:lesson_id]
      @lesson_member = current_member.lesson_members.build(lesson_id: params[:lesson_id])
    else
      @lesson_member = current_member.lesson_members.build(lesson_member_params)
    end

    if @lesson_member.save_with_remind
      redirect_to my_lesson_members_url, notice: 'Lesson member was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @lesson_member.update(lesson_member_params)
      redirect_to my_lesson_members_url, notice: 'Lesson member was successfully updated.'
    else
      render :edit
    end
  end

  def edit_quit
  end

  def update_quit
    @lesson_member.quit_note = lesson_member_params[:quit_note]
    @lesson_member.trigger_to! state: 'request_quit'
  end

  def destroy
    @lesson_member.destroy
    redirect_to my_lesson_members_url, notice: 'Lesson member was successfully destroyed.'
  end

  private
  def set_lesson_member
    @lesson_member = LessonMember.find(params[:id])
  end

  def lesson_member_params
    params.fetch(:lesson_member, {}).permit(:lesson_id, :quit_note)
  end

end

app/controllers/train/my/lessons_controller.rb
class TrainMy::LessonsController < TrainMy::BaseController
  before_action :set_lesson, only: [:show, :edit]

  def index
    l_params = {
      'lesson.type': params[:type],
      'lesson.lesson_taxon_id': params[:lesson_taxon_id],
      'lesson.title-asc': params['title-asc']
    }
    @lesson_members = current_member.lesson_members.includes(:lesson).default_where(l_params)

    q_params = params.fetch(:q, {}).permit!
    q_params.merge! params.permit(:type, 'title-asc', :lesson_taxon_id)
    q_params.merge! 'id-not': @lesson_members.pluck(:lesson_id)
    # if current_member.department
    #   @lessons = current_member.department.lessons.default_where(q_params).page(params[:page])
    # else
      @lessons = Lesson.outward.default_where(q_params).page(params[:page])
    #end

    respond_to do |format|
      format.html
      format.html.phone { render 'index', layout: 'my_phone' }
    end
  end

  def show

    respond_to do |format|
      format.html
      format.html.phone { render 'show', layout: 'my_phone' }
    end
  end

  private
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

end

app/controllers/train/my/teachers_controller.rb
class TrainMy::TeachersController < TrainMy::BaseController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
      redirect_to my_teacher_url, notice: 'Teacher was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to my_teacher_url, notice: 'Teacher was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @teacher.destroy
    redirect_to my_teacher_url, notice: 'Teacher was successfully destroyed.'
  end

  private
  def set_teacher
    @teacher = current_member&.teacher
  end

  def teacher_params
    params.fetch(:teacher, {}).permit(
      :description
    )
  end

end

app/views/edu/my/lessons/_form.html.erb
<%= form_with model: @course, local: true do |f| %>
  <%= render 'shared/error_messages', target: @course %>
  <%= f.submit %>
<% end %>

app/views/edu/my/lessons/_index.html.erb
<table class="ui bottom attached selectable table">
  <thead>
    <tr>
      <th><%= Course.human_attribute_name(:id) %></th>
      <th>
        <%= link_to Course.human_attribute_name(:title), filter_params('title-asc': 2, except: ['title-asc']) %>
      </th>
      <th><%= Course.human_attribute_name(:lecturer) %></th>
      <th><%= Course.human_attribute_name(:type) %></th>
      <th><%= Course.human_attribute_name(:limit_people) %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @courses.select { |i| i.enabled? }.each do |course| %>
    <tr>
      <td><%= course.id %></td>
      <td>
        <%= link_to course.title, my_course_path(course) %>
        <span class="<%= active_assert(course.compulsory, expected: 'ui green label', unexpected: 'ui label') %>"><%= course.compulsory_i18n %></span>
      </td>
      <td><%= course.lecturer&.name %></td>
      <td><%= course.type_i18n %></td>
      <td>
        <%= course.limit_people %> / <%= course.course_students_count %>
      </td>
      <td>
        <% unless course.is_a?(OfflineCourse) && (course.course_students_count >= course.limit_people.to_i) %>
          <%= link_to 'Select', my_course_students_path(course_id: course.id), method: :post, data: {confirm: t('.confirm')}, class: 'ui green label' %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @courses %>

app/views/edu/my/lessons/_search_form.html.erb
<%= form_with theme: 'search', model: Course.new do |f| %>
  <div class="fields">
    <%= f.text_field :name %>
    <%= f.submit %>
  </div>
<% end %>

<dl>
  <dt>Type:</dt>
  <dd class="ui labels">
    <%= link_to 'All', filter_params(except: [:type]), class: active_params(type: '', active_class: 'ui blue label', item_class: 'ui white label') %>
    <% Course.options_i18n(:type).each do |text, type| %>
      <%= link_to text, filter_params(type: type), class: active_params(type: type, active_class: 'ui blue label', item_class: 'ui white label') %>
    <% end %>
  </dd>
</dl>
<dl>
  <dt>Module:</dt>
  <dd class="ui labels">
    <%= link_to 'All', filter_params(except: [:course_taxon_id]), class: active_params(course_taxon_id: '', active_class: 'ui blue label', item_class: 'ui white label') %>
    <% CourseTaxon.all.each do |taxon| %>
      <%= link_to taxon.name, filter_params(course_taxon_id: taxon.id), class: active_params(course_taxon_id: taxon.id, active_class: 'ui blue label', item_class: 'ui white label') %>
    <% end %>
  </dd>
</dl>

app/views/edu/my/lessons/edit.html.erb
<div class="ui segment breadcrumb">
  <%= link_to 'Back', courses_path, class: 'section' %>
  <i class="fa-light fa-angle-right divider"></i>
  <div class="active section">Edit</div>
</div>

<div class="ui segment">
  <%= render 'form' %>
</div>

app/views/edu/my/lessons/index.html+phone.erb
<div class="ui top attached borderless menu">
  <%= link_to 'My Courses', my_course_students_path, class: 'item' %>
  <div class="header item">Courses</div>
</div>

<table class="ui bottom attached unstackable table">
  <thead>
    <tr>
      <th><%= Course.human_attribute_name(:id) %></th>
      <th><%= Course.human_attribute_name(:title) %></th>
      <th><%= Course.human_attribute_name(:limit_people) %></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @course_students.each do |course_student| %>
    <tr>
      <td><%= course_student.course_id %></td>
      <td>
        <%= link_to course_student.course.title, my_course_path(course_student.course_id) %>
      </td>
      <td>
        <%= course_student.course.limit_people %> / <%= course_student.course.course_students_count %>
      </td>
      <td>
        <span class="ui label"><%= course_student.state_i18n %></span>
      </td>
    </tr>
  <% end %>
  <% @courses.each do |course| %>
    <tr>
      <td><%= course.id %></td>
      <td>
        <%= link_to course.title, my_course_path(course) %>
      </td>
      <td>
        <%= course.limit_people %> / <%= course.course_students_count %>
      </td>
      <td>
        <%= link_to 'Select', my_course_students_path(course_id: course.id), method: :post, data: {confirm: t('.confirm')}, class: 'ui green label' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @courses %>

app/views/edu/my/lessons/index.html.erb
<%= render 'nav_courses' %>

<div class="ui attached segment">
  <%= render 'search_form' %>
</div>

<%= render 'index' %>

app/views/edu/my/lessons/new.html.erb
<div class="ui segment breadcrumb">
  <%= link_to 'Back', courses_path, class: 'section' %>
  <i class="fa-light fa-angle-right divider"></i>
  <div class="active section">Add</div>
</div>

<div class="ui segment">
  <%= render 'form' %>
</div>

app/views/edu/my/lessons/show.html+phone.erb
<table class="ui very basic unstackable table">
  <thead>
  <tr>
    <th class="six wide"></th>
    <th class="ten wide"></th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td class="right aligned">Course Category</td>
    <td><%= @course.course_taxon.name %></td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:title) %></td>
    <td><%= @course.title %></td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:type) %></td>
    <td><%= @course.type_i18n %></td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:description) %></td>
    <td><%= simple_format(@course.description) %></td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:lecturer) %></td>
    <td><%= @course.lecturer&.name %></td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:author) %></td>
    <td><%= @course.author&.name %></td>
  </tr>
  <tr>
    <td class="right aligned">Lecturer Desc</td>
    <td><%= simple_format(@course.lecturer&.description) %></td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:meeting_room) %></td>
    <td><%= @course.meeting_room %></td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:next_start_time) %></td>
    <td><%= @course.next_start_time %></td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:next_finish_time) %></td>
    <td><%= @course.next_finish_time %></td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:video) %></td>
    <td>
      <%= link_to @course.video.filename, rails_blob_path(@course.video, disposition: 'attachment'), target: '_blank' if @course.video.attached? %>
    </td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:en_video) %></td>
    <td>
      <%= link_to @course.en_video.filename, rails_blob_path(@course.en_video), target: '_blank' if @course.en_video.attached? %>
    </td>
  </tr>
  <tr>
    <td class="right aligned"><%= Course.human_attribute_name(:document) %></td>
    <td>
      <%= link_to @course.document.filename, rails_blob_path(@course.document), target: '_blank' if @course.document.attached? %>
    </td>
  </tr>
  </tbody>
</table>

app/views/edu/my/lessons/show.html.erb
<%= render 'nav_course' %>

<div class="ui basic segment breadcrumb">
  <%= link_to 'Back', my_courses_path, class: 'section' %>
  <i class="fa-light fa-angle-right divider"></i>
  <div class="active section"><%= @course.title %></div>
</div>

<table class="ui very basic large table">
  <thead>
    <tr>
      <th class="three wide"></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="right aligned">Course Category</td>
      <td><%= @course.course_taxon.name %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:title) %></td>
      <td><%= @course.title %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:type) %></td>
      <td><%= @course.type_i18n %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:description) %></td>
      <td><%= simple_format(@course.description) %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:lecturer) %></td>
      <td><%= @course.lecturer&.name %></td>
    </tr>
    <tr>
      <td class="right aligned">Lecturer Desc: </td>
      <td><%= simple_format(@course.lecturer&.description) %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:meeting_room) %></td>
      <td><%= @course.meeting_room %></td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:next_start_time) %></td>
      <td><time><%= @course.next_start_time.to_s(:rfc822) if @course.next_start_time %></time></td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:next_finish_time) %></td>
      <td><time><%= @course.next_finish_time.to_s(:rfc822) if @course.next_finish_time %></time></td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:video) %></td>
      <td>
        <%= render 'active_storage/attachments/list', target: @course.video %>
      </td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:en_video) %></td>
      <td>
        <%= render 'active_storage/attachments/list', target: @course.en_video %>
      </td>
    </tr>
    <tr>
      <td class="right aligned"><%= Course.human_attribute_name(:document) %></td>
      <td>
        <%= render 'active_storage/attachments/list', target: @course.document %>
      </td>
    </tr>
  </tbody>
</table>