config/routes.rb
Rails.application.routes.draw do

  scope module: 'edu' do
    resources :courses
  end

  scope :admin, module: 'edu/admin', as: 'admin' do
    
    resources :course_papers do
      get :add, on: :member
      resources :exams do
        put :refer, on: :member
        patch :score, on: :member
      end
    end
    resources :teachers do
      get :search, on: :collection
    end
    resources :exams, only: [] do
      get :todo, on: :collection
      get :cert, on: :collection
    end
  end

  scope :my, module: 'edu/my', as: 'my' do
    resources :exams, only: [] do
      post :add, on: :collection
      get :certification, on: :collection
    end
    resources :courses, only: [:index, :show] do
      collection do
        get :plan
      end
      resources :exams, shallow: true do
        match :finish, on: :member, via: [:get, :put]
      end
    end
    resources :course_students do
      get 'quit' => :edit_quit, on: :member
      patch 'quit' => :update_quit, on: :member
    end
    resource :teacher
  end

end

app/models/edu/course_paper.rb
module Edu
  class CoursePaper < ApplicationRecord
    include Model::CoursePaper
  end
end

app/models/edu/exam.rb
module Edu
  class Exam < ApplicationRecord
    include Notice::Ext::Notifiable if defined? RailsNotice
    include Model::Exam
  end
end

app/models/edu/exam_reviewer.rb
module Edu
  class ExamReviewer < ApplicationRecord
    include Model::ExamReviewer
  end
end

app/models/edu/model/course/case_study.rb
module RailsEdu::Course::CaseStudy

  def enabled?
    self.next_finish_time && self.next_finish_time > Time.now
  end

end

app/models/edu/model/course/offline_course.rb
module RailsEdu::Course::OfflineCourse

  def enabled?
    self.next_finish_time && self.next_finish_time > Time.now
  end

end

app/models/edu/model/course/online_course.rb
module RailsEdu::Course::OnlineCourse

  def enabled?
    true
  end

end

app/models/edu/model/course/share_course.rb
module RailsEdu::Course::ShareCourse

  def enabled?
    self.next_finish_time && self.next_finish_time > Time.now
  end

end

app/models/edu/model/course_paper.rb
module Edu
  module Model::CoursePaper
    extend ActiveSupport::Concern

    included do
      belongs_to :course, optional: true
      has_many :exams, dependent: :nullify
      has_one_attached :document
    end

  end
end

app/models/edu/model/course_paper/exam_paper.rb
module RailsEdu::CoursePaper::ExamPaper
  extend ActiveSupport::Concern
  included do
    after_initialize if: :new_record? do
      self.title ||= "Exam_#{self.course&.title}"
    end
  end
  
end

app/models/edu/model/course_paper/survey_paper.rb
module RailsEdu::CoursePaper::SurveyPaper
  extend ActiveSupport::Concern

  included do

  end

end

app/models/edu/model/exam.rb
module Model::Exam
  extend ActiveSupport::Concern
  include StateMachine

  included do
    belongs_to :course_paper, optional: true
    belongs_to :course, optional: true
    belongs_to :member
    belongs_to :reviewer, class_name: 'Member', inverse_of: 'review_exams', counter_cache: 'review_exams_count', optional: true
    has_one :course_student, ->(o){ where(member_id: o.member_id) }, primary_key: 'course_id', foreign_key: 'course_id'
    serialize :answer_detail, Hash

    enum state: {
      init: 'init',
      finished: 'finished',
      evaluated: 'evaluated'
    }
    scope :processing, -> { default_where(state: 'evaluated', 'answer_mark-gte': 60).or(Exam.where(state: ['init', 'finished'])) }

    after_initialize if: :new_record? do
      self.state ||= 'init'
      self.course_id = self.course_paper&.course_id
    end
  end

  def set_finish
    return if self.finished?
    self.set_reviewer
    self.trigger_to! state: 'finished'
    if self.course_paper.is_a?(ExamPaper)
      ExamMailer.review(self.id).deliver_later
      ExamJob.perform_later(self.id)
    end
  end

  def custom_link
    if course_paper.link.present?
      to_survey_monkey
    else
      to_one_drive
    end
  end

  def set_reviewer
    if self.course_paper.is_a?(CertifiablePaper)
      self.reviewer_id = self.member.exam_reviewers.order(review_exams_count: :asc).first.id
    end
  end

  def reviewer
    if super
      super
    elsif self.member.tutor
      self.member.tutor
    else
      self.member.parent || Member.find_by(email: 'mingyuan.qin@mdpi.com')
    end
  end

  def close_date
    if course_paper.is_a?(CertifiablePaper)
      Time.now.change(hour: 18, min: 15)
    end
    #(Time.now + 10.minutes).to_s(:iso8601)
  end

  def enabled?
    (Time.now > Time.now.change(hour: 16, min: 59)) && self.link
  end

  def sync_answer
    self.sync_answer_detail
    self.sync_answer_result
  end

  def set_referenced
    self.class.transaction do
      self.update(referenced: true)
      Exam.where.not(id: self.id).where(course_paper_id: self.course_paper_id).update_all(referenced: false)
    end
  end

  def referenced_exam
    @referenced_exam ||= Exam.find_by(course_paper_id: self.course_paper_id, referenced: true)
  end

end

app/models/edu/model/exam_reviewer.rb
module RailsEdu::ExamReviewer
  extend ActiveSupport::Concern

  included do
    belongs_to :exam
    belongs_to :member
    belongs_to :reviewer, class_name: 'Member'
  end

end

app/models/edu/model/plan_attender.rb
module RailsEdu::PlanAttender
  extend ActiveSupport::Concern

  included do
    belongs_to :course
    belongs_to :course_student
    belongs_to :crowd, optional: true
    belongs_to :lesson, optional: true

    before_validation :sync_course_student
  end

  def sync_course_student
    if course_student
      self.attender_type = course_student.student_type
      self.attender_id = course_student.student_id
    end
  end

end

app/models/edu/model/teacher.rb
module RailsEdu::Teacher
  extend ActiveSupport::Concern
  
  included do
    has_many :review_exams, class_name: 'Exam', foreign_key: :reviewer_id, inverse_of: 'reviewer'
  end


end

app/models/edu/plan_attender.rb
module Edu
  class PlanAttender < ApplicationRecord
    include Model::PlanAttender
  end
end

app/models/rails_edu/courses/case_study.rb
class CaseStudy < Course

  def enabled?
    self.next_finish_time && self.next_finish_time > Time.now
  end

end

app/models/rails_edu/courses/offline_course.rb
class OfflineCourse < Course

  def enabled?
    self.next_finish_time && self.next_finish_time > Time.now
  end

end

app/models/rails_edu/courses/offline_lesson.rb
class OfflineCourse < Course

  def enabled?
    self.next_finish_time && self.next_finish_time > Time.now
  end

end

app/models/rails_edu/courses/online_lesson.rb
class OnlineCourse < Course

  def enabled?
    true
  end

end

app/models/rails_edu/courses/share_lesson.rb
class ShareCourse < Course

  def enabled?
    self.next_finish_time && self.next_finish_time > Time.now
  end

end

app/views/edu/courses/_filter.html.erb
<div class="ui attached segment">

<%= form_with theme: 'search', model: Course.new do |f| %>
  <div class="fields">
    <%= f.text_field :name %>
    <%= f.submit %>
  </div>
<% end %>

</div>

app/views/edu/courses/_form.html.erb
<%= form_with model: @course do |f| %>
  <%= render 'shared/error_messages', target: @course %>
  <%= f.submit %>
<% end %>

app/views/edu/courses/_show_table.html.erb
<table class="ui very basic large table">
  <thead>
    <tr>
      <th class="six wide">
        <%= link_to t('.edit'), edit_edu_course_path(@course), class: 'ui mini blue right floated button', remote: true %>
      </th>
      <th class="ten wide"></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/edu/courses/edit.html.erb
<div class="ui segment breadcrumb">
  <%= link_to 'Back', edu_courses_path, class: 'section' %>
  <i class="fa-light fa-angle-right divider"></i>
  <div class="active section">Edit</div>
</div>

<div class="ui segment">
  <%= render 'form' %>
</div>

app/views/edu/courses/edit.js.erb
$('#modal').replaceWith('<%= j(render 'edit') %>');
$('#modal').modal('show');
remote_js_load('<%= raw remote_js_load %>')

app/views/edu/courses/index.html.erb
<div class="ui top attached borderless menu">
  <div class="header item">Edu Courses</div>
</div>

<%= render 'filter' %>

<table class="ui bottom attached selectable table">
  <thead>
    <tr>
      <th><%= Course.human_attribute_name(:id) %></th>
      <th>
        <%= link_to 'New Edu Course', new_edu_course_path, class: 'ui teal button', remote: true %>
      </th>
    </tr>
  </thead>
  <tbody>
  <% @courses.each do |course| %>
    <tr>
      <td><%= course.id %></td>
      <td>
        <%= link_to edu_course_path(course), data: { tooltip: t('.show') }, remote: true, class: 'ui mini circular icon button' do %>
          <i class="fa-light fa-circle-info"></i>
        <% end %>
        <%= link_to edit_edu_course_path(course), data: { tooltip: t('.edit') }, remote: true, class: 'ui mini circular icon button' do %>
          <i class="fa-light fa-pencil"></i>
        <% end %>
        <%= link_to edu_course_path(course), method: :delete, data: { tooltip: t('.destroy'), confirm: t('.confirm') }, class: 'ui mini circular icon button' do %>
          <i class="fa-light fa-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= paginate @courses %>

app/views/edu/courses/new.html.erb
<div class="ui segment breadcrumb">
  <%= link_to 'Back', edu_courses_path, class: 'section' %>
  <i class="fa-light fa-angle-right divider"></i>
  <div class="active section">Add</div>
</div>

<div class="ui segment">
  <%= render 'form' %>
</div>

app/views/edu/courses/new.js.erb
$('#modal').replaceWith('<%= j(render 'new') %>');
$('#modal').modal('show');
remote_js_load('<%= raw remote_js_load %>')

app/views/edu/courses/show.html.erb
<div class="ui segment breadcrumb">
  <%= link_to 'Back', edu_courses_path, class: 'section' %>
  <i class="fa-light fa-angle-right divider"></i>
  <div class="active section">Show</div>
</div>

<%= render 'show_table' %>

app/views/edu/courses/show.js.erb
$('#modal').replaceWith('<%= j(render 'show') %>');
$('#modal').modal('show');
remote_js_load('<%= raw remote_js_load %>')